-- =============================================================
-- 内嵌 AI 意图 SDK · 意图三表 DDL（PostgreSQL 12+）
--
-- 与 deploy/sql/{02-intent-admin,04-intent-spec,05-intent-executor}.sql 的
-- MySQL 版本语义等价——那三张表是 SDK 自有资产，本文件是其 PostgreSQL 方言版本。
-- 菜单 / 角色 / 演示用户等数据属于宿主应用（ruoyi-office），不在 SDK 交付范围内。
--
-- 零建表替代方案：SDK 提供内存与会话文件仓储（intent.host.storage=FILE），
-- 不开这三张表也能完整运行；开表是为了让意图可在后台增删改并即时生效。
-- =============================================================

-- 1. 意图配置：上架状态 + 可见角色（roles 为角色编码 JSON 数组，["*"] = 不限制）
CREATE TABLE IF NOT EXISTS intent_config (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id   varchar(128) NOT NULL,
    enabled     boolean      NOT NULL DEFAULT true,
    roles       varchar(512) NOT NULL DEFAULT '["*"]',
    remark      varchar(500)          DEFAULT NULL,
    creator     varchar(64)           DEFAULT '',
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater     varchar(64)           DEFAULT '',
    update_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     boolean      NOT NULL DEFAULT false,
    tenant_id   bigint       NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_intent_config_intent ON intent_config (intent_id);

COMMENT ON TABLE  intent_config            IS '意图配置';
COMMENT ON COLUMN intent_config.enabled    IS '是否上架';
COMMENT ON COLUMN intent_config.roles      IS '可见角色编码（JSON 数组，["*"]=不限制）';
COMMENT ON COLUMN intent_config.tenant_id  IS '租户编号';

-- 2. 意图规范：IntentSpec 完整定义的 DB 化存储（启动时 classpath YAML 播种，已存在则跳过）
CREATE TABLE IF NOT EXISTS intent_spec (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_id   varchar(128) NOT NULL,
    spec_json   text         NOT NULL,
    source      varchar(16)  NOT NULL DEFAULT 'custom',
    remark      varchar(500)          DEFAULT NULL,
    creator     varchar(64)           DEFAULT '',
    create_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater     varchar(64)           DEFAULT '',
    update_time timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     boolean      NOT NULL DEFAULT false,
    tenant_id   bigint       NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_intent_spec_intent ON intent_spec (intent_id);

COMMENT ON TABLE  intent_spec           IS '意图规范';
COMMENT ON COLUMN intent_spec.spec_json IS 'IntentSpec 完整定义（JSON）';
COMMENT ON COLUMN intent_spec.source    IS '来源（builtin=classpath 种子 / custom=后台创建）';

-- 3. 执行器档案：ExecutorProfile 完整定义的 DB 化存储
CREATE TABLE IF NOT EXISTS intent_executor (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executor_id  varchar(128) NOT NULL,
    profile_json text         NOT NULL,
    source       varchar(16)  NOT NULL DEFAULT 'custom',
    remark       varchar(500)          DEFAULT NULL,
    creator      varchar(64)           DEFAULT '',
    create_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater      varchar(64)           DEFAULT '',
    update_time  timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted      boolean      NOT NULL DEFAULT false,
    tenant_id    bigint       NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_intent_executor_executor ON intent_executor (executor_id);

COMMENT ON TABLE  intent_executor              IS '执行器档案';
COMMENT ON COLUMN intent_executor.profile_json IS 'ExecutorProfile 完整定义（JSON）';
COMMENT ON COLUMN intent_executor.executor_id  IS '执行器标识（IntentSpec.executor 引用）';

-- 4. update_time 自动维护：等价于 MySQL 的 ON UPDATE CURRENT_TIMESTAMP
CREATE OR REPLACE FUNCTION intent_touch_update_time() RETURNS trigger AS $$
BEGIN
    NEW.update_time := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_intent_config_touch ON intent_config;
CREATE TRIGGER trg_intent_config_touch BEFORE UPDATE ON intent_config
    FOR EACH ROW EXECUTE FUNCTION intent_touch_update_time();

DROP TRIGGER IF EXISTS trg_intent_spec_touch ON intent_spec;
CREATE TRIGGER trg_intent_spec_touch BEFORE UPDATE ON intent_spec
    FOR EACH ROW EXECUTE FUNCTION intent_touch_update_time();

DROP TRIGGER IF EXISTS trg_intent_executor_touch ON intent_executor;
CREATE TRIGGER trg_intent_executor_touch BEFORE UPDATE ON intent_executor
    FOR EACH ROW EXECUTE FUNCTION intent_touch_update_time();