-- =============================================================
-- 内嵌 AI 意图 SDK · 意图三表 DDL（Oracle 12c+）
--
-- 与 MySQL 版本（deploy/sql/0{2,4,5}-*.sql）语义等价。
-- 说明：Oracle 无 CREATE TABLE IF NOT EXISTS，用 PL/SQL 幂等包装；
--       bit 用 NUMBER(1)，datetime 用 TIMESTAMP，mediumtext 用 CLOB；
--       update_time 的 ON UPDATE 语义用触发器实现。
-- =============================================================

-- 1. 意图配置
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'INTENT_CONFIG';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE intent_config (
                id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                intent_id   VARCHAR2(128) NOT NULL,
                enabled     NUMBER(1)     DEFAULT 1 NOT NULL,
                roles       VARCHAR2(512) DEFAULT '["*"]' NOT NULL,
                remark      VARCHAR2(500),
                creator     VARCHAR2(64)  DEFAULT '',
                create_time TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                updater     VARCHAR2(64)  DEFAULT '',
                update_time TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                deleted     NUMBER(1)     DEFAULT 0 NOT NULL,
                tenant_id   NUMBER(19)    DEFAULT 0 NOT NULL
            )]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_intent_config_intent ON intent_config (intent_id)';
    END IF;
END;
/

COMMENT ON TABLE  intent_config           IS '意图配置';
COMMENT ON COLUMN intent_config.enabled   IS '是否上架';
COMMENT ON COLUMN intent_config.roles     IS '可见角色编码（JSON 数组，["*"]=不限制）';
COMMENT ON COLUMN intent_config.tenant_id IS '租户编号';

-- 2. 意图规范
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'INTENT_SPEC';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE intent_spec (
                id          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                intent_id   VARCHAR2(128) NOT NULL,
                spec_json   CLOB          NOT NULL,
                source      VARCHAR2(16)  DEFAULT 'custom' NOT NULL,
                remark      VARCHAR2(500),
                creator     VARCHAR2(64)  DEFAULT '',
                create_time TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                updater     VARCHAR2(64)  DEFAULT '',
                update_time TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                deleted     NUMBER(1)     DEFAULT 0 NOT NULL,
                tenant_id   NUMBER(19)    DEFAULT 0 NOT NULL
            )]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_intent_spec_intent ON intent_spec (intent_id)';
    END IF;
END;
/

COMMENT ON TABLE  intent_spec           IS '意图规范';
COMMENT ON COLUMN intent_spec.spec_json IS 'IntentSpec 完整定义（JSON）';
COMMENT ON COLUMN intent_spec.source    IS '来源（builtin=classpath 种子 / custom=后台创建）';

-- 3. 执行器档案
DECLARE
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM USER_TABLES WHERE TABLE_NAME = 'INTENT_EXECUTOR';
    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE intent_executor (
                id           NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                executor_id  VARCHAR2(128) NOT NULL,
                profile_json CLOB          NOT NULL,
                source       VARCHAR2(16)  DEFAULT 'custom' NOT NULL,
                remark       VARCHAR2(500),
                creator      VARCHAR2(64)  DEFAULT '',
                create_time  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                updater      VARCHAR2(64)  DEFAULT '',
                update_time  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                deleted      NUMBER(1)     DEFAULT 0 NOT NULL,
                tenant_id    NUMBER(19)    DEFAULT 0 NOT NULL
            )]';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_intent_executor_execut ON intent_executor (executor_id)';
    END IF;
END;
/

COMMENT ON TABLE  intent_executor              IS '执行器档案';
COMMENT ON COLUMN intent_executor.profile_json IS 'ExecutorProfile 完整定义（JSON）';
COMMENT ON COLUMN intent_executor.executor_id  IS '执行器标识（IntentSpec.executor 引用）';

-- 4. update_time 自动维护（等价于 MySQL 的 ON UPDATE CURRENT_TIMESTAMP）
CREATE OR REPLACE TRIGGER trg_intent_config_touch
    BEFORE UPDATE ON intent_config FOR EACH ROW
BEGIN
    :NEW.update_time := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_intent_spec_touch
    BEFORE UPDATE ON intent_spec FOR EACH ROW
BEGIN
    :NEW.update_time := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_intent_executor_touch
    BEFORE UPDATE ON intent_executor FOR EACH ROW
BEGIN
    :NEW.update_time := SYSTIMESTAMP;
END;
/